"use client"

import { useState, useRef, useEffect } from "react"
import { MessageCircle, X, Send } from "lucide-react"

interface ChatMessage {
  id: string
  text: string
  sender: "user" | "bot"
  timestamp: string
}

export function FloatingChat() {
  const [showChat, setShowChat] = useState(false)
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: "1",
      text: "Welcome to FairMonie Support! How can I assist you today?",
      sender: "bot",
      timestamp: new Date().toLocaleTimeString(),
    },
  ])
  const [inputValue, setInputValue] = useState("")
  const [isTyping, setIsTyping] = useState(false)
  const messagesEndRef = useRef<HTMLDivElement>(null)

  // Auto-scroll to bottom when new messages arrive
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" })
  }, [messages])

  const handleSendMessage = () => {
    if (!inputValue.trim()) return

    // Add user message
    const userMessage: ChatMessage = {
      id: String(Date.now()),
      text: inputValue,
      sender: "user",
      timestamp: new Date().toLocaleTimeString(),
    }

    setMessages((prev) => [...prev, userMessage])
    setInputValue("")

    // Simulate bot response with typing indicator
    setIsTyping(true)
    setTimeout(() => {
      const botResponse: ChatMessage = {
        id: String(Date.now() + 1),
        text: generateSmartResponse(inputValue),
        sender: "bot",
        timestamp: new Date().toLocaleTimeString(),
      }
      setMessages((prev) => [...prev, botResponse])
      setIsTyping(false)
    }, 1000)
  }

  const generateSmartResponse = (userMessage: string): string => {
    const lowerMessage = userMessage.toLowerCase()

    if (
      lowerMessage.includes("faircode") ||
      lowerMessage.includes("fair code") ||
      lowerMessage.includes("code")
    ) {
      return "A FairCode is a necessary tool used to withdraw your funds securely. It secures your transactions and is protected and generated by CBN (Central Bank of Nigeria). You can buy a FairCode from the dashboard in the 'Buy Faircode' section for ₦7,500."
    }
    if (
      lowerMessage.includes("loan") ||
      lowerMessage.includes("borrow") ||
      lowerMessage.includes("credit")
    ) {
      return "You can apply for loans directly from the dashboard. Loans up to ₦1,000,000 are available with no collateral documentation needed. The loan approval process is quick and takes just 5 minutes! Go to the Loan section to get started."
    }
    if (
      lowerMessage.includes("withdraw") ||
      lowerMessage.includes("bank") ||
      lowerMessage.includes("account")
    ) {
      return "To withdraw funds, go to the Withdraw section and enter your bank account details. You'll need a valid FairCode to complete your withdrawal. Your withdrawal will be processed within 24 hours."
    }
    if (lowerMessage.includes("payment") || lowerMessage.includes("confirm")) {
      return "Your payment is being processed. If it's not confirmed within 24 hours, please contact our support team through email at sopportteam54@gmail.com or Telegram at t.me/vercelsupport."
    }
    if (
      lowerMessage.includes("bonus") ||
      lowerMessage.includes("claim") ||
      lowerMessage.includes("welcome")
    ) {
      return "You can claim a welcome bonus of ₦250,000 from your dashboard. Just click the 'Claim Bonus' button to get started!"
    }
    if (
      lowerMessage.includes("hello") ||
      lowerMessage.includes("hi") ||
      lowerMessage.includes("hey")
    ) {
      return "Hello! I'm here to help you with any questions about FairMonie. What would you like to know? (loans, withdrawals, faircodes, payments, etc.)"
    }

    return "Thanks for reaching out! I'm here to help. Could you tell me more about what you need? (You can ask about loans, withdrawals, faircodes, payments, or how to use our services)"
  }

  return (
    <>
      {/* Floating Chat Button - Fixed positioning with animation */}
      <button
        onClick={() => setShowChat(true)}
        className="floating-button fixed right-3 sm:right-6 bottom-3 sm:bottom-6 w-12 sm:w-14 h-12 sm:h-14 rounded-full bg-[#1a9b5c] text-white shadow-2xl flex items-center justify-center hover:scale-110 active:scale-95 transition-transform z-40"
      >
        <MessageCircle className="w-5 sm:w-6 h-5 sm:h-6" fill="currentColor" />
      </button>

      {/* Full Screen Chat Modal */}
      {showChat && (
        <div className="fixed inset-0 bg-white z-50 flex flex-col">
          {/* Chat Header */}
          <div className="bg-[#1a9b5c] text-white p-4 flex items-center gap-3 flex-shrink-0 shadow-md">
            <div className="w-12 h-12 rounded-full bg-white/20 flex items-center justify-center text-xl">
              💚
            </div>
            <div className="flex-1">
              <h3 className="font-semibold">FairMonie Assistant</h3>
              <p className="text-xs text-green-100 flex items-center gap-1">
                <span className="w-2 h-2 bg-green-300 rounded-full animate-pulse"></span>
                Online • Ready to help
              </p>
            </div>
            <button
              onClick={() => setShowChat(false)}
              className="text-white text-2xl hover:opacity-80 transition"
            >
              <X className="w-6 h-6" />
            </button>
          </div>

          {/* Chat Messages */}
          <div className="flex-1 overflow-y-auto p-3 sm:p-4 space-y-3 sm:space-y-4 bg-gray-50">
            {messages.map((msg) => (
              <div
                key={msg.id}
                className={`flex ${
                  msg.sender === "user" ? "justify-end" : "justify-start"
                } px-1 sm:px-0`}
              >
                <div
                  className={`max-w-xs sm:max-w-sm md:max-w-md px-3 sm:px-4 py-2 sm:py-3 rounded-2xl text-sm sm:text-base ${
                    msg.sender === "user"
                      ? "bg-[#1a9b5c] text-white rounded-br-none break-words"
                      : "bg-white text-gray-800 rounded-bl-none border border-gray-200 break-words"
                  }`}
                >
                  <p className="text-xs sm:text-sm">{msg.text}</p>
                  <p
                    className={`text-xs mt-1 ${
                      msg.sender === "user"
                        ? "text-green-100"
                        : "text-gray-500"
                    }`}
                  >
                    {msg.timestamp}
                  </p>
                </div>
              </div>
            ))}

            {/* Typing indicator */}
            {isTyping && (
              <div className="flex justify-start">
                <div className="bg-white text-gray-800 px-4 py-3 rounded-2xl rounded-bl-none border border-gray-200">
                  <div className="flex gap-2">
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce"></div>
                    <div
                      className="w-2 h-2 bg-gray-400 rounded-full animate-bounce"
                      style={{ animationDelay: "0.1s" }}
                    ></div>
                    <div
                      className="w-2 h-2 bg-gray-400 rounded-full animate-bounce"
                      style={{ animationDelay: "0.2s" }}
                    ></div>
                  </div>
                </div>
              </div>
            )}

            <div ref={messagesEndRef} />
          </div>

          {/* Chat Input */}
          <div className="border-t border-gray-200 bg-white p-2 sm:p-4 flex gap-2 flex-shrink-0">
            <input
              type="text"
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              onKeyPress={(e) => {
                if (e.key === "Enter" && !e.nativeEvent.isComposing) {
                  handleSendMessage()
                }
              }}
              placeholder="Ask me anything..."
              className="flex-1 px-3 sm:px-4 py-2 sm:py-3 bg-gray-100 rounded-full border border-gray-300 focus:outline-none focus:border-[#1a9b5c] text-xs sm:text-sm"
            />
            <button
              onClick={handleSendMessage}
              disabled={!inputValue.trim()}
              className="w-9 sm:w-10 h-9 sm:h-10 bg-[#1a9b5c] hover:bg-[#168a4f] disabled:opacity-50 text-white rounded-full flex items-center justify-center transition flex-shrink-0"
            >
              <Send className="w-4 sm:w-5 h-4 sm:h-5" />
            </button>
          </div>
        </div>
      )}
    </>
  )
}
